### PR TITLE
Add Coverage reports

### PR DESCRIPTION
**Pull request by felixfbecker**
Adds uploads to https://codecov.io/gh/aaronpowell/ps-nvmw (you'd need to enable it)

This PR is based off #29, coverage is added in the last commit

### CODE REVIEW

**Comment by aaronpowell** [comment]
ooops, merge conflict!

**Comment by felixfbecker** [comment]
Hmm, looks like there is a problem https://codecov.io/gh/aaronpowell/ps-nvmw/commit/e31f4ad63b9446b0aad0a01cd26418fa41e5057c

**Comment by felixfbecker** [comment]
Ahh, Pester only outputs a summary that is not understood at all by codecov...
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.0//EN" "report.dtd">
<report name="Pester (11/08/2017 02:20:00)"><sessioninfo id="this" start="1510107595764" dump="1510107600257" /><counter type="INSTRUCTION" missed="105" covered="53" /><counter type="LINE" missed="80" covered="36" /><counter type="METHOD" missed="6" covered="4" /><counter type="CLASS" missed="0" covered="1" /></report>
```

**Comment by felixfbecker** [comment]
https://github.com/pester/Pester/issues/212

**Comment by aaronpowell** [comment]
Oh rats 😢

**Pull request merged**
