### PR TITLE
moving some local dev scripts out into a dot folder so they are exclu…

### PR DESCRIPTION
**Pull request by aaronpowell**
…ded from publish

### CODE REVIEW

**Comment by felixfbecker** [comment]
You need to change the AppVeyor and Travis config

**Comment by aaronpowell** [comment]
@felixfbecker done - also fixing the merge issue

**Comment by felixfbecker** [comment]
Ah sorry I didn't see you were targeting the semver branch. I just rebased and squashed all my commits.

**Comment by felixfbecker** [comment]
Confirmed that VS Code still works

image

**Comment by aaronpowell** [comment]
Wait, where'd these conflicts come from?

**Comment by aaronpowell** [comment]
Oh did you do a squish on the `semver` branch?

**Comment by felixfbecker** [comment]
Yes. I can fix up if you want, let me know.

**Comment by aaronpowell** [comment]
Yeah, I've gotta jump into a meeting, unless you have something better to do at midnight 😛

**Comment by felixfbecker** [comment]
It's 3 PM in my time zone 😄

**Comment by aaronpowell** [comment]
Oh, then you can totally fix it 😛 

I thought you were in Germany

**Comment by felixfbecker** [comment]
I'm in San Francisco now - I should update my profile 😄

**Comment by felixfbecker** [comment]
There ya go

**Review by felixfbecker — APPROVED** [review]

**Pull request merged**
