### PR TITLE
Log to Write-Information, not by outputting strings

### PR DESCRIPTION
**Pull request by felixfbecker**
This allows log output to be controlled by log levels.

### CODE REVIEW

**Comment by aaronpowell** [comment]
Hmm, those test failures are odd...

**Comment by felixfbecker** [comment]
I know why, they asserted what I changed ;)

**Comment by aaronpowell** [comment]
Oh!

Shows how much attention I pay to how our tests work 😝

**Comment by aaronpowell** [comment]
Want to do a minor version bump in the psd1 and then it can be merged and released.

**Comment by felixfbecker** [comment]
Can't we merge this first and release it together with the other PR? (bump the version on master)

**Review by aaronpowell — APPROVED** [review]

**Pull request merged**
