### PR TITLE
Updating the definition file for v2 release

### PR DESCRIPTION
**Pull request by aaronpowell**
Last little tweak for v2, getting the `psd1` updated. @felixfbecker I've also listed you as an author 😄

### CODE REVIEW

**Review by felixfbecker — APPROVED** [review]

**Comment by aaronpowell** [comment]
Let's hope that Travis doesn't take 3 hours again 😛

**Comment by felixfbecker** [comment]
Since you are not touching code I would be fine if you merged without CI.

Btw you probably want to update the version number in appveyor.yml (this is why I just use an incrementing number, I don't want to update it all the time 😛 )

**Comment by aaronpowell** [comment]
I have to change the settings to override the checks so we don't have to wait for builds to complete 😛

**Comment by felixfbecker** [comment]
Oh, I think we should remove https://github.com/aaronpowell/ps-nvm/blob/master/NodeVersionManager.psm1 as part of 2.0

**Comment by aaronpowell** [comment]
Ah yes, meant to do that. It doesn't get published in the module anymore anyway.

**Comment by aaronpowell** [comment]
Made it so as an admin I can bypass checks 😈

**Pull request merged**
