### PR TITLE
Install-NodeVersion: take into account .nvmrc & package.json

### PR DESCRIPTION
**Pull request by rvdginste**
If no version is given, then scan the current directory for either
a .nvmrc file or a package.json file.  Behavior is identical to the
Set-NodeVersion cmdlet.

### CODE REVIEW

**Comment by aaronpowell** [comment]
Hmm, wonder why the Linux build dies... Weird.

Do you think it'd be possible to add a test to cover this scenario? I wouldn't want the test coverage to drop ;)

**Comment by rvdginste** [comment]
Sure, I'll give it a go.

The linux build fails because it cannot find the dotnet-sdk-2.0.0 package, even though at first sight, the package still seems to be available. Maybe I'll see if I can run that build locally.

**Comment by nschonni** [comment]
Fix for the linux build issue over in #77

**Comment by aaronpowell** [comment]
There we go, we're getting code coverage listed again.

**Comment by aaronpowell** [comment]
@rvdginste You can mock the `Get-Content` call here: https://github.com/aaronpowell/ps-nvm/blob/master/nvm.tests.ps1#L167

Then you could just simulate the JSON structure for the different conditional paths.

**Comment by rvdginste** [comment]
@aaronpowell I added some tests in. I made integration-tests just like the other Install-NodeVersion tests. Is this ok?

**Review by aaronpowell — APPROVED** [review]

**Comment by aaronpowell** [comment]
Rolling out in release 2.4.0

**Pull request merged**
