### PR TITLE
Run integration tests in Travis

### PR DESCRIPTION
**Pull request by felixfbecker**

### CODE REVIEW

**Comment by aaronpowell** [comment]
This is why I shouldn't review PR's when I'm watching TV and only half paying attention!

**Comment by felixfbecker** [comment]
This is why I shouldn't do PRs at 2AM

**Comment by felixfbecker** [comment]
So looks  like these tests actually fail with 
```
Version v9.0.0 is already installed, use -Force to reinstall
```
no idea why they don't do that on Windows, but shouldn't there be an `AfterEach` that cleans up installed versions from the previous test?

**Comment by felixfbecker** [comment]
Probably related to that test using `$TestDrive` in opposite to the other tests. But I gotta catch some sleep now 💤

**Pull request merged**
