### PR TITLE
Support Semver

### PR DESCRIPTION
**Pull request by felixfbecker**
First shot at full semver range support for all versions.
After a lot of tinkering I went with the approach of installing semver.net through nuget and using the `Range` and `Version` types directly because their oeprator overloading makes working with them a breeze.

I added a csproj to define the dependencies as project.json and packages.config seem to all be deprecated and psproj doesn't support nuget dependencies. One disadvantage right now is that this dumps a lot of files into the repo root. An alternative would be to release all to-be-published files into a target directory.

The most interesting thing about this is that it now supports reading the version from package.json `engines` field. So you could write your `prompt` function so that you can `cd` into any open source repo and it automatically selects the correct node version.

TODO
- [x] Add a test for reading from package.json
- [ ] If we shoot for 2.0.0, remove deprecated things

### CODE REVIEW

**Comment by aaronpowell** [comment]
The first thing that I'm observing is that we end up with a lot of junk artifacts within the package that we publish:

Contents of the package

I'd prefer that we do stuff within a "dot folder" which `nuget pack` (that `Publish-Module` internally uses) will ignore.

**Comment by felixfbecker** [comment]
Yeah I agree. It sucks that PowerShellGallery doesn't seem to support something like a `.psgalleryignore` file. We definitely need the SemVer.dll though. I don't know what is the prettiest way to do this. One option is to copy the "to-be-published" stuff into a target folder, which would at least save us from `bin` and `obj`.

**Comment by aaronpowell** [comment]
Another thought, rather than using a `csproj` or anything and have a pre-install I think the module should do the install itself and do it via just NuGet.exe.

So I think the workflow would be:

- Module is imported
- Checks if `SemVer.dll` is in the expected path
- If it's not check that `NuGet.exe` is in path, or at an expected path
- If it's not -> Download from `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`
- Once `NuGet.exe` is available install `SemVer.dll`
- Continue on

This means that the module is fully self contained, it will bootstrap itself as required, and on subsequent module imports it shouldn't download anything, as they are already available.

Now not 100% sure about the cross-platform installing, maybe it'd have to use `dotnet` or you can just do something really hacky like use `Invoke-WebRequest` to just download the NuGet package directly, and skip NuGet completely.

**Comment by felixfbecker** [comment]
I don't really like the idea of downloading nuget dynamically on installation of the PS module. Imo the PowerShell module should contain the assemblies needed. I can see us getting into a rabbit hole of trying to maintain the nuget installation on macos, Linux and Windows. It was a pain to get into Linux, if you google for it the guides actually tell you to install Mono first and then run nuget.exe with mono (which I _think_ is what made it finally work in Travis, nothing else worked). That's quite a dependency for this use case. To get NuGet on macOS I think you just have to install the dotnet core SDK from a pkg, which is also quite a dependency. Considering all this I would even rather have a few KB of trash files in the module than a script that has to pull down and install all that stuff just to get a DLL.

**Comment by aaronpowell** [comment]
Yeah that's a valid point about the expanding dependencies.

Let me have a think, I still dislike the idea on pushing out a bunch of junk files.

**Comment by felixfbecker** [comment]
I think I found an easy solution, we can specify a `Delete` task that is run after publish that deletes the unwanted files: https://docs.microsoft.com/en-us/visualstudio/msbuild/delete-task

**Comment by felixfbecker** [comment]
I managed to configure it so that the only thing produced is SemVer.dll

**Comment by aaronpowell** [comment]
Cool that looks better, but I still like the idea of pushing the `csproj` file out to a dot folder or something. Also what's not clear for a local dev/source install that you need to do the install step. I really strive to have as minimal steps to setup a project for local dev, if you can _clone -> F5_ without other steps I'm really happy (and that's what I'm driving at with #41)

**Comment by felixfbecker** [comment]
I added the publish task to tasks.json so that running `task Run Pester` will automatically first install dependencies before running the tests.

**Comment by felixfbecker** [comment]
I don't know why the import of the DLL fails on AppVeyor - I ran the tests on my Windows machine and it's working

**Comment by felixfbecker** [comment]
Local:
```
$ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.64
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.64
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

$ dotnet --info
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```
AppVeyor:
```
$PSVersionTable
Name                           Value                                                                                                                                                                                                 
----                           -----                                                                                                                                                                                                 
PSVersion                      5.1.14393.1715                                                                                                                                                                                        
PSEdition                      Desktop                                                                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                               
BuildVersion                   10.0.14393.1715                                                                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                                                                                                               
dotnet --info
.NET Command Line Tools (2.0.2)
Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\
Microsoft .NET Core Shared Framework Host
  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by felixfbecker** [comment]
So on Windows 10 Fall Creators update / .NET Framework 4.7.1 this "just works": https://github.com/PowerShell/PowerShell/blob/master/docs/cmdlet-example/command-line-simple-example.md#using-a-net-standard-20-based-binary-module-in-windows-powershell

**Comment by felixfbecker** [comment]
Got it working 🎉

**Comment by felixfbecker** [comment]
I think this is mostly ready to go, but we should talk about the possible breaking changes:
- I changed the return type of `Get-InstalledNodeVersions` to return SemVer Version objects instead of strings. When casted to a string they become the same string again though. I think this is a good change because the Version class implements Comparable, so a user can sort the versions semantically as defined in the semver spec with `Sort-Object` and also compare them with `-gt` and `-lt` operators.
- This imports a .netstandard 2.0 DLL, which is supposed to be a works-everywhere assembly, BUT: during getting AppVeyor to work, I already noticed that it doesn't work if you don't have the latest .NET Framework (4.7.1) installed because 4.6.x had a bug with that kind of interop. That means this potentially adds an environmental dependency.
- The `-Version` argument previously did fuzzy matching and now uses semver ranges, which should result in the same result, but I am not sure. E.g. `v4` should be interpreted as `^4.0.0` which should result in the same version being installed as before.

Solutions for this:
- We might be able to do some magic where we try to import the DLL but resort to the old behaviour if it fails. This would add a _lot_ of complexity (maintaining the old fuzzy matching) and could be very unexpected (different return types)
- Upping the major version to 2.0.0. I think this is the right thing to do, it won't break anyone and align with semver, but new users will just `Install-Module` and get these awesome features.

Wdyt?

**Comment by aaronpowell** [comment]
The change to the hard dependency on .NET 4.7.x do bother me a little, possibly need to have that registered somewhere, likely in `DotNetFrameworkVersion = ''` of the `psd1` file.

I wonder if you can't use the `RequiredAssemblies = @()` to load `SemVer.dll` instead of importing it manually...

I do agree though that if we do have to take it that we treat it as a major release and go to v2 of the module. You mention you'd want to remove the deprecated things as well in doing this, what's deprecated?

**Comment by felixfbecker** [comment]
Oh, I didn't know that existed. Let's use that if it works!

I only thought of https://github.com/aaronpowell/ps-nvm/blob/master/NodeVersionManager.psm1

**Comment by aaronpowell** [comment]
I'm happy where things are in this PR though, so I'm going to merge it but I *won't* cut a release. Instead I'll create a release milestone that we can use to track what needs to be done to finish the release.

**Review by aaronpowell — APPROVED** [review]

**Comment by aaronpowell** [comment]
Once Travis completes I'll merge this into `master`

**Comment by felixfbecker** [comment]
Yeah I'm fine with that. Does PS Gallery support some concept of unstable release channels or prereleases?
What's the work you want to do before 2.0.0?

**Comment by aaronpowell** [comment]
It should, it's a NuGet feed under the hood, but I've never looked into it.

Milestone is setup: https://github.com/aaronpowell/ps-nvm/milestone/1

**Comment by felixfbecker** [comment]
I also don't know whether this still supports PS 3.0. If we want to continue support that, we should add it to the build matrix, because I have no way to test it

**Pull request merged**
