### PR TITLE
Linux support

### LINKED ISSUE #35: Linux support
Just opening this to to track it.

### PR DESCRIPTION
**Pull request by aaronpowell**
Closes #35

### CODE REVIEW

**Comment by aaronpowell** [comment]
@felixfbecker I think this should be right for Linux support. Did some prelim testing on WSL (Ubuntu install) and I also think I got Travis configured.

I pushed Travis build logic into a script.

Edit: Well, seems I've broken travis! That's a tomorrow problem, unless you want to have a crack @felixfbecker

**Comment by aaronpowell** [comment]
So wait, is there a decrease in the coverage from this PR?

**Comment by felixfbecker** [comment]
Weird. I would feel more confident about this if we had an integration test that actually checked the output of `node --version` to make 100% sure it was installed correctly, works, is in the PATH and the right version.

**Comment by felixfbecker** [comment]
According to coverage this part is never hit:

image

**Comment by felixfbecker** [comment]
I also noticed this:
```
$ pwsh -c "{ Import-Module $env:HOME/CodeCovIo.psm1; $res = Invoke-Pester -CodeCoverage nvm.psm1; Export-CodeCovIoJson -CodeCoverage $res.CodeCoverage -RepoRoot $pwd -Path coverage.json; if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed." } }"
.FailedCount: command not found
```
Tests are apparently failing but the `throw` is not working.

**Comment by aaronpowell** [comment]
Ah so it seems to not publish the Linux coverage report

**Comment by felixfbecker** [comment]
Well, there is no test output either, so looks like the tests didn't run correctly.

https://travis-ci.org/aaronpowell/ps-nvmw/jobs/302765018#L582-L589

**Comment by aaronpowell** [comment]
Well that's odd...

**Comment by felixfbecker** [comment]
Got it working, not sure what was broken before though.

**Comment by felixfbecker** [comment]
Hmm, the import of the codecov helper fails...

**Comment by felixfbecker** [comment]
I think Travis replaces `$env` with the value of the `$env` environment variable, which is empty, so the script executed is `:HOME`.

**Comment by felixfbecker** [comment]
FINALLY got coverage working too. What a ride. This PR is very important, I discovered we weren't actually running tests on master anymore.

**Review by felixfbecker — APPROVED** [review]

**Comment by felixfbecker** [comment]
Make sure to squash merge this 😅

**Comment by aaronpowell** [comment]
I forgot the branch policy prevents pushing to `master`, as that was how I intended to cut the release 😛

**Pull request merged**
