### PR TITLE
Improve Install/Remove-NodeVersion

### PR DESCRIPTION
**Pull request by thisjustin816**
- Add support for installing/uninstalling multiple versions at once
- Add pipeline support to Remove-NodeVersion and Set-NodeVersion
- Return only version folders with executables in `Get-NodeVersions`
- Fix issue where a version wouldn't install because the install path went over the windows path limit
- Fix issue where the MSI fails or node can't actually be called after installing and no error is thrown

### CODE REVIEW

**Comment by aaronpowell** [comment]
ok, looks like the build pipeline is stuffed. I'll have to find some time to work on that and get some proper reviews done.

**Comment by thisjustin816** [comment]
All tests passing on Windows
image

**Comment by aaronpowell** [comment]
Finally got around to merging this. There was some problem with the cross-platform with cross platform that I solved in #91 

I'll do a new version shortly.

**Comment by aaronpowell** [comment]
And released as `2.5.1` (I stuffed up the GitHub Actions for `2.5.0` so it didn't deploy 🤣)

**Pull request merged**
