### PR TITLE
Persist node version choice on Mac/Linux

### LINKED ISSUE #24: Persistent default on macOS
nvm allows to set the "default" version that persists after terminal, but the `-Persist` option in ps-nvmw currently doesn't seem to work on macOS (is that a bug in .NET core?).

Some options that make work:
- Add to `/etc/paths`
- Use `launchctl` to set a persistent `PATH`
- Add to `profile.ps1`

### PR DESCRIPTION
**Pull request by elsassph**
Fixes #24 

**Implementation:**

- when adding `-Persist`, the version is written to a `default` file (similar to `.nvmrc`) in the `vs` folder where the node binaries are downloaded,
- depending on the scope (`User`, `Machine`) a call to `Set-NodeVersion` (without arguments) is appended to the appropriate `profile.ps1`.
- `Set-NodeVersion` when called without version parameter will fallback to the version written in the `default` file.

**Notes:**

- This is similar to the way `nvm-sh` functions (storing the version in a `default` file and setting the path when the user profile scripts is executed),
- It may be worth documenting how to set the `Machine` configuration as it requires escalation:

```
sudo pwsh -c 'Set-NodeVersion 10 -Persist Machine'
```

### CODE REVIEW

**Comment by elsassph** [comment]
Not sure why tests don't pass... I'll need to try with Windows maybe.

**Comment by aaronpowell** [comment]
_sigh_

Looks like something has changed in Travis since last set of build runs. Maybe we should move to GitHub actions 😜

**Comment by aaronpowell** [comment]
@felixfbecker are you able to run the tests locally on a mac? I can try Windows next week.

**Comment by elsassph** [comment]
Any progress?

**Comment by aaronpowell** [comment]
And released as `2.5.1` (I stuffed up the GitHub Actions for `2.5.0` so it didn't deploy 🤣)

**Pull request merged**
